# Generated by Django 3.2.3 on 2025-01-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='S', max_length=50),
        ),
        migrations.AlterField(
            model_name='productimagesurl',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
